### ISSUE TITLE
Extract 3D contour mask 

### ISSUE THREAD

**Issue by sama2689** [dicompyler/dicompyler-core#223]
Is there some way to extract the 3D mask of a struct? i.e. a binary rank 3 tensor which corresponds to struct outlines? I am looking to computer the overlap between GTVs in two different rt-struct files (I am doing this manually right now by extracting 2 masks and computing the overlap).

I had found the `dicompylercore.dvhcalc.get_contour_mask` function but it seems like this is only for single slices from the struct at a time?

Thanks in advance

**Comment by bastula** [comment]
As of right now, there is no function to pull a 3D mask. It is done in 2D serially so that memory usage doesn't grow significantly.

**Comment by sama2689** [comment]
I have looked into RT-Utils but ran into a different issue [here](https://github.com/qurit/rt-utils/issues/19), so was hopeful that dicompylercore could do it.
Is it possible then to run the get_contour_mask in 2D over all slices and then merge them to get a 3D mask? I was unsure of the syntax with which I would call get_contour_mask so was unsure how to go about doing something like this.

**Comment by bastula** [comment]
You can `get_contour_mask` and stack the resultant `numpy.array` with `numpy.vstack` or `numpy.hstack`, but in this implementation, it requires the dose grid. Since the RTStruct is stored in patient coordinates, it needs a conversion back to pixel coordinates.

You could do it without the dose grid but set your own arbitrary grid size for voxellization.

Maybe @cutright has some expertise in this area?

**Comment by cutright** [comment]
[DVHA](https://github.com/cutright/DVH-Analytics) calculate PTV overlap... wouldn't be hard to add other targets.

Personally, I found it much easier to work with [Shapely](https://shapely.readthedocs.io/en/stable/manual.html).  DVHA creates a shapely object per slice for each ROI, then just uses the `Polgyon.intersection` to create a new shape.  I think you'll find this to be much faster and retain better resolution.  If you're only looking for overlap, you only need to keep one of these at a time. If you want a new object, DVHA does that for the total PTV creation, I can point you to that too if it's of interest.

Here is the overlap calculation: https://github.com/cutright/DVH-Analytics/blob/b0be7031ccf7f8ef33dc26b441c02a9bbc3efc9c/dvha/tools/roi_geometry.py#L248-L285

The only snag here is that my ROI format might be a little different than what you have because I work with the format in the DVHA DB rather than dicompyler-core directly, but not a big hurdle. Each input parameter into the function linked above uses the following format:
```
# "sets of points" objects
#     dictionaries using str(z) as keys
#         where z is the slice or z in DICOM coordinates
#         each item is a list of points representing a polygon,
#         each point is a 3-item list [x, y, z]
```

Admittedly, there is plenty of room for better performance (e.g., using more Numpy objects), but hopefully this is helpful?

**Comment by sama2689** [comment]
Definitely very helpful, I'm trying it with DVHA now, though have had some installation hiccups. Once those are sorted I think the overlap function from DVHA should do the trick, I don't actually need the mask if I can compute the overlap directly.

**Comment by sama2689** [comment]
Is it possible to get a 2D mask via a shapely object? I have been struggling to figure out quite how to do this and so far my [stackoverflow post ](https://stackoverflow.com/questions/67708224/shapely-polygon-to-binary-mask/67720519?noredirect=1#comment119700279_67720519)on the subject has not yielded a response that worked.
