### ISSUE TITLE
Calculate structure volume

### ISSUE THREAD

**Issue by sama2689** [dicompyler/dicompyler-core#253]
This should be a simple syntax question, but I can't quite figure out how to calculate the structure volume without computing a DVH (which can be time consuming). I can see that a parsed rtss has an attribute called GetStructureVolume which takes in inputs of coords and the thickness, so I thought I can extract the coords with `rtss.GetStructureCoordinates(roi_number)` and the thickness in one go, but the function `CalculatePlaneThickness(self, planesDict):` does not make sense to me, what should the input of this function be to calculate the thickness?

I want my final script to extract a volume in one line like

`rtss.CalculateStructureVolume(rtss.GetStructureCoordinates(roi_number),rtss.CalculatePlaneThickness(planesDict))`

But can't figure out how to generate planesDict for my structure of interest.

Thanks

**Comment by bastula** [comment]
The unit tests can sometimes serve as an example for each function, but I will go through a complete example.

https://github.com/dicompyler/dicompyler-core/blob/de6a0ed7f3a928399f799bce0acb6018e595a8bf/tests/test_dicomparser.py#L198-L211

Basically you could do the following in 2 lines:
```
planes = rtss.GetStructureCoordinates(roi_number)
volume = rtss.CalculateStructureVolume(planes, rtss.CalculatePlaneThickness(planes))
```

You could shorten it to 1 line, but it may take longer to calculate the coordinates as a tuple since it would have to do it twice:
```
volume = rtss.CalculateStructureVolume(rtss.GetStructureCoordinates(roi_number), rtss.CalculatePlaneThickness(rtss.GetStructureCoordinates(roi_number)))
```

**Comment by sama2689** [comment]
Thanks, that works!

**Comment by bastula** [comment]
I have pushed docstring updates and thus documentation so function arguments should be more clear. Thanks for all your questions and comments!
