### ISSUE TITLE
DVH dose calculation

### ISSUE THREAD

**Issue by dktan** [dicompyler/dicompyler-core#3]
I've been working on a DicomRT project and your dicom parser has been very helpful.

I also been looking at your old dicom rt project at https://github.com/bastula/dicompyler
I noticed that the dvh dose calculation in these two project are quite different. And the result from the old version match your dicompyler app. Also the structure volume from the two version are different and the new version match the app. That confuse me.

and the code from old version: 

def get_dvh_min(dvh):
    '''Return minimum dose to ROI derived from cDVH.'''

```
# ROI volume (always receives at least 0% dose)
v1 = dvh[0]

j = 1
jmax = len(dvh) - 1
mindose = 0
while j < jmax:
    if dvh[j] < v1:
        mindose = (2*j - 1)/2.0
        break
    else:
        j += 1

return mindose
```

seem it gives dose base on a index?..

Hope you can clear my confusion.
Thanks a lot.

p.s. I think we are using the same testing data set here.
![qq20160919-0](https://cloud.githubusercontent.com/assets/12505414/18651951/8459efc0-7e83-11e6-9d84-1f96418660a9.png)
##

**Comment by bastula** [comment]
The calculation should be the approximately the same. In the new ``dvh`` module, it will return absolute dose by default, unless you request relative dose (based on the prescription dose). In this dataset it is 14 Gy.

You can do that by typing: ``calcdvh.relative_dose(14).max``, etc. for each statement, or by setting the relative dose via ``calcdvh.rx_dose = 14`` and then accessing each statistic. 

Check out the examples in more detail in the accompanying [Jupyter notebook](https://github.com/bastula/dicom-notebooks/blob/master/dicompyler-core_usage.ipynb). You can see this example specifically on line 8.

Looking at the differences between dicompyler and the new ``dvh`` module, the difference should be only within the 100th place for each statistic, which in IMHO is not that significant. The reason for this is due to the way that the histogram is derived, which is now more accurate in dicompyler-core.

**Comment by bastula** [comment]
I think this issue is resolved so closing.
