### ISSUE TITLE
dvh.max gives IndexError

### ISSUE THREAD

**Issue by nicocrm** [dicompyler/dicompyler-core#93]
Hello and thank you for the project.

I am using dicompyler-core 0.5.4 to extract statistics and I have been running into an exception with certain DCM files.  When calculating `dvh.max`, the following error is thrown:

```
 File "/home/nico/.local/share/virtualenvs/dcm-extractor-8Y6EYVZw/lib/python3.7/site-packages/dicompylercore/dvh.py", line 269, in max
    return diff.bins[1:][diff.counts > 0][-1]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 1
```

This seems to happen whenever dvh.counts is either empty, or has all same values (such that dvh.diff.counts is all 0s).

Please let me know if I can assist in troubleshooting.

**Comment by bastula** [comment]
I understand what you are saying. Do you have a test case that you can run or any artificial data that can reproduce the issue? Maybe we can fix this line and also add a unit test for it?

**Comment by nicocrm** [comment]
It's a bit artificial, but I could write a test where I set dvh.counts to an empty array.
Alternatively, I have an anonymized DCM file that exhibits the behavior - I could add it to the existing test data and write a test case around it, the downside is it will add about 4M to the repo.

**Comment by thomaspheiffer** [comment]
I also just ran into this issue in the last day or two. In my case it seemed to be for a contour (closed planar) that somehow resulted in `calculate_contour_dvh` returning a volume of 0, later leading to the `hist` values getting zeroed out here:

https://github.com/dicompyler/dicompyler-core/blob/f5f9fa770d0573373510135863fa2933919cdba7/dicompylercore/dvhcalc.py#L219

**Comment by bastula** [comment]
> It's a bit artificial, but I could write a test where I set dvh.counts to an empty array.
> Alternatively, I have an anonymized DCM file that exhibits the behavior - I could add it to the existing test data and write a test case around it, the downside is it will add about 4M to the repo.

I think the artificial counts array is fine. I have done that for some of the unit tests already.

**Comment by bastula** [comment]
> I also just ran into this issue in the last day or two. In my case it seemed to be for a contour (closed planar) that somehow resulted in `calculate_contour_dvh` returning a volume of 0, later leading to the `hist` values getting zeroed out here:
> 
> [dicompyler-core/dicompylercore/dvhcalc.py](https://github.com/dicompyler/dicompyler-core/blob/f5f9fa770d0573373510135863fa2933919cdba7/dicompylercore/dvhcalc.py#L219)
> 
> Line 219 in [f5f9fa7](/dicompyler/dicompyler-core/commit/f5f9fa770d0573373510135863fa2933919cdba7)
> 
>  hist = hist * volume / sum(hist)

Can you describe the structure data? Do you know if the volume was calculated correctly?

**Comment by bastula** [comment]
I think your PR is fine, but I want to think about why this situation is arising. As far as I am aware, it only happens if a structure is too small to be encompassed by a dose voxel (i.e. the dose grid resolution is more coarse than the structure coordinates)? Thus no counts or volume arrays are generated.

**Comment by nicocrm** [comment]
It's possible.  I looked at my test case and the structure that was giving me the error is about 3x5mm, and only in 1 plane.  The dose grid is a 3mm resolution so maybe it didn't quite hit it?  If you have a structure that is completely outside of the dose you would have the same behavior since the counts would be all 0.
It could be an error in the source data too - we have a QA software so we process dicoms that are sometimes of questionable quality.

**Comment by bastula** [comment]
Have you tried using the interpolation feature (introduced in 0.5.4) when calculating DVHs? https://dicompyler-core.readthedocs.io/en/latest/usage.html (at the bottom)

This was introduced to alleviate the coarse dose grid / small structure volume issue.

I suppose I haven't run into the issue you guys have described because I usually detect for an empty DVH (mostly either due to no contour data present or situation described above) in my user code and then don't process it any further. My assumption is that in your data processing pipeline, you must be requesting the DVH stats on an instance of the DVH class regardless of whether it is empty. With respect to that, I think the PR makes sense to the end user.
